const enter=document.querySelector('#enter');
enter.addEventListener('click',()=>{document.body.classList.remove('waiting');document.body.classList.add('entered');document.querySelector('#main').inert=false;setTimeout(()=>document.querySelector('#entrance').remove(),1700);});
const notes=[
['不必完美','你不用时时刻刻闪闪发光。\n连偶尔暗下来的你，\n也一样值得被喜欢。'],['慢慢长大','不用急着成为大人。\n二十岁有二十岁的风，\n你只管慢慢走。'],['保留天真','愿你见过世界的复杂，\n仍愿意为一朵花停下，\n为一颗糖开心。'],['好好睡觉','把烦恼暂时交给夜晚。\n醒来时，\n新的太阳会找到你。'],['常常快乐','快乐不必很盛大。\n喜欢的歌，温热的饭，\n也能撑起一个好日子。'],['勇敢出发','想去的地方，就去看看。\n山水很远，\n但第一步就在脚下。'],['允许迷路','偶尔不知道往哪走，\n也没有关系。\n月亮不会催你赶路。'],['珍惜自己','请把温柔留一份给自己。\n你也应该是，\n被认真照顾的那个人。'],['有人懂你','愿有人听懂你的笑，\n也听懂你\n没有说出口的话。'],['有梦可追','那些藏在心里的愿望，\n不必说给所有人听。\n一点一点，靠近就好。'],['自在如风','不必活成标准答案。\n你可以写一首诗，\n也可以成为旷野。'],['心有微光','如果夜色很深，\n记得你的心里，\n也有一盏小小的灯。'],['吃好每餐','再忙，也要好好吃饭。\n生活的温柔，\n有时藏在一碗热汤里。'],['偶尔偷懒','歇一歇，不是落后。\n岸边的风景，\n也值得你多看一眼。'],['拥抱晴天','愿阴天短一点，\n晴天长一点。\n愿你笑的日子，多一点。'],['不惧告别','有些风，只陪一程。\n但每一次出发，\n都会遇见新的春天。'],['被爱包围','愿你被爱得很具体。\n有回应，有陪伴，\n也有不必开口的惦念。'],['记住今天','记住二十岁的这一夜。\n月亮、山水、这一卷，\n都在认真为你庆祝。'],['未来很长','还没见过的风景，\n还没发生的好事，\n都在未来等着你。'],['一直是你','无论后来走到哪里，\n愿你仍然喜欢自己。\n而我，仍然喜欢你。']];
const list=document.querySelector('#notes-list'),dialog=document.querySelector('#note-dialog');
notes.forEach(([title,body],i)=>{const b=document.createElement('button');b.className='note';b.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')} / 20</span><strong>${title}</strong><span class="open-mark">展开这一笺</span>`;b.addEventListener('click',()=>{document.querySelector('#note-number').textContent=`第 ${String(i+1).padStart(2,'0')} 笺`;document.querySelector('#note-title').textContent=title;document.querySelector('#note-body').textContent=body;dialog.showModal()});list.append(b)});
document.querySelector('.close-note').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const chapters=[['voyage','启舟'],['her','她'],['twenty','二十'],['notes','二十笺'],['wishes','愿'],['meeting','相逢'],['letter','给你'],['dawn','天明']];
const nav=document.querySelector('.chapter-nav');chapters.forEach(([id,label])=>{const a=document.createElement('a');a.href='#'+id;a.setAttribute('aria-label',label);a.innerHTML=`<span>${label}</span>`;nav.append(a)});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const chapterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){nav.querySelectorAll('a').forEach(a=>a.setAttribute('aria-current',a.hash==='#'+e.target.id?'true':'false'))}}),{rootMargin:'-35% 0px -35% 0px',threshold:0});document.querySelectorAll('.act').forEach(el=>chapterObserver.observe(el));
document.querySelectorAll('.wish').forEach(b=>b.addEventListener('click',()=>{b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')==='true'?'false':'true');const n=document.querySelectorAll('.wish[aria-pressed=true]').length;document.querySelector('.wish-status').textContent=n===4?'愿望已随舟出发。愿所有美好，都慢慢抵达。':n?`已有 ${n} 份祝愿，随月光亮起。`:'四份心愿，等一阵温柔的风。'}));
document.querySelector('#replay').addEventListener('click',()=>{window.scrollTo({top:0,behavior:'instant'});document.body.classList.remove('entered');requestAnimationFrame(()=>requestAnimationFrame(()=>document.body.classList.add('entered')))});
let audioContext,waterGain,playing=false;const sound=document.querySelector('#sound');sound.addEventListener('click',async()=>{try{if(!audioContext){audioContext=new (window.AudioContext||window.webkitAudioContext)();const buffer=audioContext.createBuffer(1,audioContext.sampleRate*4,audioContext.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+Math.random()*.04-.02)/1.02;data[i]=last*3}const source=audioContext.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioContext.createBiquadFilter();filter.type='lowpass';filter.frequency.value=450;waterGain=audioContext.createGain();waterGain.gain.value=0;source.connect(filter).connect(waterGain).connect(audioContext.destination);source.start()}await audioContext.resume();playing=!playing;waterGain.gain.setTargetAtTime(playing?.13:0,audioContext.currentTime,1.2);sound.textContent=playing?'水声 · 开':'水声 · 关';sound.setAttribute('aria-pressed',String(playing));sound.setAttribute('aria-label',playing?'关闭水声':'开启水声')}catch{sound.textContent='水声暂不可用'}});
let scrollPending=false;window.addEventListener('scroll',()=>{if(!scrollPending){requestAnimationFrame(()=>{const y=window.scrollY,ratio=Math.min(1,y/(document.documentElement.scrollHeight-innerHeight));document.querySelector('.landscape').style.transform=`scale(1.04) translateY(${-Math.min(y*.008,30)}px)`;document.querySelector('.landscape').style.filter=`brightness(${.72+ratio*.3})`;scrollPending=false});scrollPending=true}},{passive:true});
